using Microsoft.Office.Interop.Excel;
using System.Runtime.InteropServices;
using Excel = Microsoft.Office.Interop.Excel;
using Microsoft.CSharp;
using Application = Autodesk.Revit.ApplicationServices.Application;





//Start Excel and get Application object.
            //create a WorkSheet
            var excelApp = new Excel.Application();
            // Make the object visible.
            excelApp.Visible = true;

            // Create a new, empty workbook and add it to the collection returned
            var workBook = excelApp.Workbooks.Add();

            // This example uses a single workSheet. The explicit type casting is
            // removed in a later procedure.
            Excel._Worksheet workSheet = (Excel.Worksheet)excelApp.ActiveSheet;

            workSheet.Cells[1, "A"] = "Foo";
            workSheet.Cells[1, "B"] = "Bar";

            string Directory = ("@C:\\Users\\sam.roberts\\Desktop\\Carbon Assesment Test\\Coding");
            
            // save the workbook
            workBook.SaveAs(Directory + "\\" + "ProjectInfo.xlsx");
